### ISSUE TITLE
Provide information whether the user is authenticated

### ISSUE THREAD

**Issue by nanoant** [poolpOrg/filter-rspamd#1]
So I am running OpenSMTPD 6.6.0p0 from Git since yesterday, everything seems to work fine except DKIM signing for outgoing mail.
Upgraded from some ooooold version that was providing ooooold Rspamd and DKIM signer filters 😆 
Now this `filter-rspamd` is expected to do both I presume.

However, I don't see a clear way to tell Rspamd that it should sign my outgoing mail, quoting https://rspamd.com/doc/modules/dkim_signing.html
> To be eligible for signing, a mail must be received from an authenticated user OR a reserved (local) IP address OR an address in the sign_networks map (if defined)

From the description above only "authenticated user" flag is something that is reliable for me. I cannot do any assumptions based on IP, because IP reported to Rspamd is my client IP which depending where I am can be anything. Also I don't want to have Spam check on my outgoing mail, because it does not make sense.

The [Rspamd Protocol](https://rspamd.com/doc/architecture/protocol.html#http-headers) provides `User` field for that purpose, but I can see in `filter-rspamd` code that this field is not supplied when SMTP client was authenticated in OpenSMTPD. Also it seems that OpenSMTPD does not provide this information to their filters (or maybe I am wrong?)

Or maybe there is another way to distinguish outgoing and incoming mail? @poolpOrg How do you do it? 😉 

Here's an anonymized excerpt from my config:
~~~
filter "rspamd" proc-exec "/usr/local/bin/filter-rspamd"

listen on myipv4 port 25  hostname mydomain tls pki mydomain filter "rspamd"
listen on myupv6 port 25  hostname mydomain tls pki mydomain filter "rspamd"
listen on myipv4 port 587 hostname mydomain tls-require pki mydomain auth mask-src filter "rspamd"
listen on myipv6 port 587 hostname mydomain tls-require pki mydomain auth mask-src filter "rspamd"
~~~

Many thanks for this effort. I also became a mean inferior patron of your project 🙄 . Let's see where this goes.
Best regards,
Adam

**Comment by poolpOrg** [comment]
Nice catch, your use-case doesn't seem covered at all.

> The Rspamd Protocol provides User field for that purpose, but I can see in filter-rspamd code that this field is not supplied when SMTP client was authenticated in OpenSMTPD. Also it seems that OpenSMTPD does not provide this information to their filters (or maybe I am wrong?)

Actually, OpenSMTPD can provide that information to filters through the link-auth event if they request it but `filter-rspamd` does not request it and does not pass the User header to rspamd. This shouldn't be too hard to fix, I'll try to get you a fix ready this week.

> Many thanks for this effort. I also became a mean inferior patron of your project 🙄

Thanks :-)

**Comment by poolpOrg** [comment]
Can you pull the latest filter-rspamd from github and give it another try ?

It now register for link-auth to listen to authentication events, associates the username to the session if the authentication was successful, and passes the User header to Rspamd if a username is associated to the session.

Without it:

> 2019-08-27 20:06:38 #40290(normal) <4bc5db>; task; rspamd_task_write_log: id: <undef>, qid: <63a80eae>, ip: 127.0.0.1, (default: T (add header): [13.40/15.00] [BROKEN_H
EADERS(10.00){},MISSING_MID(2.50){},MISSING_DATE(1.00){},MIME_GOOD(-0.10){text/plain;},ARC_NA(0.00){},FROM_HAS_DN(0.00){},MIME_TRACE(0.00){0:+;},RCPT_COUNT_ONE(0.00){1;
},RCVD_COUNT_ONE(0.00){1;},RCVD_TLS_ALL(0.00){},TO_DN_ALL(0.00){},TO_EQ_FROM(0.00){}]), len: 263, time: 17.67110824584961ms real, 9.270574ms virtual, dns req: 0, digest
: <05da526278916b967da93e20f648ff4c>

With it:

> 2019-08-27 20:08:33 #40290(normal) <84f3ed>; task; rspamd_task_write_log: id: <undef>, qid: <c3efc994>, ip: 127.0.0.1, user: tester, (default: T (add header): [13.40/15.00] [BROKEN_HEADERS(10.00){},MISSING_MID(2.50){},MISSING_DATE(1.00){},MIME_GOOD(-0.10){text/plain;},ARC_NA(0.00){},FROM_HAS_DN(0.00){},MIME_TRACE(0.00){0:+;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ONE(0.00){1;},RCVD_TLS_ALL(0.00){},RCVD_VIA_SMTP_AUTH(0.00){},TO_DN_ALL(0.00){},TO_EQ_FROM(0.00){}]), len: 278, time: 4.951000213623047ms real, 3.4951400000000006ms virtual, dns req: 0, digest: <ec939232ae49c2385ca3078678f49bb5>

Note the username after the IP address in the second line.

This should be enough to get your use-case covered, can you please confirm so that I can tag a new release and update the OpenBSD port ?

edit: @nanoant just notifying you to make sure this doesn't go unnoticed ;-)

**Comment by nanoant** [comment]
@poolpOrg I have installed and tested it, and it works now great. Thank you!
One remark (maybe to put somewhere in the README, is that `allow_username_mismatch = false;` has to be specified in `/etc/rspamd/local.d/dkim_signing.conf` if using Unix usernames (without domain), nicely put at: https://github.com/rspamd/rspamd/issues/1768

**Comment by poolpOrg** [comment]
Neat
I'll update README and roll a new release this week,

Thanks !
