### ISSUE TITLE
filter-rspamd crash

### ISSUE THREAD

**Issue by poolpOrg** [poolpOrg/filter-rspamd#11]
rspamdQuery() ends by writing back the session to the sessions map however this should not be done this way but through a channel so we don't have concurrent writes to the map.

**Comment by whataboutpereira** [comment]
I've been meaning to ask - does OpenSMTPD send mails concurrently to filters?

**Comment by poolpOrg** [comment]
depends on what you mean by concurrently:

OpenSMTPD guarantees that filters will receive lines atomically so that two sessions will not result in broken protocol lines, but two concurrent sessions will result in interleaved protocol lines, so you cannot assume that because you're reading a line from a session, the next line will also be for that session.

In the case of this issue, the fix is not hard, we should have a goroutine in charge of updating the session map and all updates go through a channel.

**Comment by whataboutpereira** [comment]
I had been thinking of using a channel mainly because if I understand correctly the current rspamd  query will block the whole filter. If multiple sessions are in flight concurrently, that will be bad on throughput.

Another optimization I've been thinking about is to pass the actual session as a pointer to all the reporter functions etc.

**Comment by poolpOrg** [comment]
> I had been thinking of using a channel mainly because if I understand correctly the current rspamd query will block the whole filter. If multiple sessions are in flight concurrently, that will be bad on throughput.
> 

I'm unsure I understand, the rspamd query happens in a go routine so this should not block the filter and my initial testings involved interleaving sessions to make sure they didn't block each other. Did you observe otherwise ?

> Another optimization I've been thinking about is to pass the actual session as a pointer to all the reporter functions etc.

I was actually going to do that and this might even remove the need for a channel in this case since the map would only be updated from the main go routine and a session would never be accessed by more than a go routine.

**Comment by whataboutpereira** [comment]
Oh, you are right, I seem to have missed "go". I was reading about channels and thought that's what we need here. :)

**Comment by poolpOrg** [comment]
Basically if we don't go pointers, we need channels, if we go pointers we don't (in this case).

I think the easiest is to switch to pointers

**Comment by poolpOrg** [comment]
could use a review @whataboutpereira :

https://github.com/poolpOrg/filter-rspamd/tree/fix-issue-11

**Comment by poolpOrg** [comment]
committed fix with your comments taken into account
