### ISSUE TITLE
Verbose X-Spam-Symbols.

### ISSUE THREAD

**Issue by whataboutpereira** [poolpOrg/filter-rspamd#16]
What do you think about having another argument to the script that would enable different levels of verbosity to X-Spam-Symbols?

We could then go from:

BAYES_SPAM
BAYES_SPAM(5.10)
BAYES_SPAM(5.10)[100.00%]

Rspamd supplies all that info anyway.

**Comment by poolpOrg** [comment]
I don't know, I'm not a big fan of having arguments unless we're forced to.

The X-Spam-Symbols header I committed was to get us closer to the `rspamc` output and make sure we had at least that level of detail in the filter that will be released with OpenBSD 6.6.

Now that filter 0.1.3 is released, I think we can work towards making the output more compact and provide an additional level of detail.

**Comment by poolpOrg** [comment]
merged !
