### ISSUE TITLE
Dead, blocked or misconfigured Rspamd url.

### ISSUE THREAD

**Issue by whataboutpereira** [poolpOrg/filter-rspamd#19]
I'm in the process of moving our server to a new machine bit by bit and testing Rspamd over a network. While everything works nicely with Rspamd over network (or locally) there isn't actually any notification if Rspamd request fails and mails are passed.

Should the filter maybe log if Rspamd http requests fail?

I also thought about pinging Rspamd server at startup with rspamd/ping, but that might not be a good idea if Rspamd starts after OpenSMTPD.

**Comment by poolpOrg** [comment]
Oops didn't see that issue.

Yes, ping at startup doesn't work as it doesn't prevent rspamd from falling down right after the ping and, at least on openbsd, smtpd is going to be started _before_ rspamd.

Logging is a good idea, the filter has been around for a little while now and we might even reconsider the "bypass filter if rspamd is down" to replace it with a 421 server internal error.

**Comment by whataboutpereira** [comment]
Putting this in production this minute.

**Comment by poolpOrg** [comment]
merged !

**Comment by whataboutpereira** [comment]
Wonderful, thanks.
