### ISSUE TITLE
filter-rspamd broken

### ISSUE THREAD

**Issue by ghost** [poolpOrg/filter-rspamd#25]
For some reason, I think that with the latest snapshot version of rspamd, filter-rspamd has stopped working. In the interim, I've disabled that filter and emails are again being delivered to my inbox. I am happy to do whatever debugging you guys would like me to. Please tell me how I can help. Thanks much!

**Comment by whataboutpereira** [comment]
Did you manage to solve it?

**Comment by ghost** [comment]
No, I didn't. I think the problem lies with rspamd and not the filter
because it was working this morning. All of a sudden I stopped receiving
emails and I am chocking it up to some issue with them. A check of the
rspamd logs showed numerous ANN errors. It's frustrating because there are
no reports of any issues on rspamd mailing lists.

**Comment by whataboutpereira** [comment]
> No, I didn't. I think the problem lies with rspamd and not the filter because it was working this morning. All of a sudden I stopped receiving emails and I am chocking it up to some issue with them. A check of the rspamd logs showed numerous ANN errors. It's frustrating because there are no reports of any issues on rspamd mailing lists.
> […](#)

Maybe try with an empty Redis database (back it up first). Iirc some neural problems needed a fresh database to fix.

**Comment by ghost** [comment]
Just tried that and still emails are not being delivered to my inbox. Now I
am starting to wonder if there wasn't a change in the rspamd in snapshots
that broke filter-rspamd after all. I deleted the /var/rspamd/dump.rdb file
and restarted rspamd.

**Comment by whataboutpereira** [comment]
Did you see Rspamd scanning the messages in its logs? What do OpenSMTPD logs look like when delivery fails?

**Comment by ghost** [comment]
No, I don't see rspamd scanning the messages in the logs. Also, there is no
failure in the OpenSMTPD logs despite having log verbose enabled. I see
that a connection has been made to OpenSMTPD but no errors ever show up.

**Comment by whataboutpereira** [comment]
What version of OpenSMTPD, filter-rspamd, Rspamd, OS? How is your filter configured?

**Comment by ghost** [comment]
My apologies for taking a bit to get back to you. I am running OpenSMTPD
6.6.1, Rspamd 2.1p1, and filter-rspamd 0.1.4. Below is my complete
smtpd.conf

pki "mail" cert "/etc/ssl/mail.crt"
pki "mail" key "/etc/ssl/private/mail.key"

table aliases file:/etc/mail/aliases
table credentials passwd:/etc/mail/credentials
table relays file:/etc/mail/relays
table rejects file:/etc/mail/rejects
table virtuals file:/etc/mail/virtuals

filter check_rejects phase connect match rdns regex <rejects> \
        disconnect "554 Access Denied"
filter check_rdns phase connect match !rdns \
        disconnect "554 No Reverse DNS"
filter rspamd proc-exec "filter-rspamd"

listen on socket
listen on lo
listen on egress tls pki "mail" \
        filter {check_rejects, check_rdns, rspamd}
listen on egress port submission tls-require pki "mail" \
        auth <credentials> filter {check_rejects, check_rdns, rspamd}

action "local_mail" mbox alias <aliases>
action "virtual_mail" maildir "/var/vmail/%{dest.domain}/%{dest.user}" junk
\
        virtual <virtuals>
action "outbound" relay

match for local action "local_mail"
match from any for domain "example.com" action "virtual_mail"
match auth from any for any action "outbound"
match for any action "outbound"

Hope this helps somewhat!

**Comment by ghost** [comment]
I should also add that I am running OpenBSD-current and below is the uname
output:
OpenBSD meow.goblackcat.com 6.6 GENERIC#493 amd64

**Comment by ghost** [comment]
I just updated to the latest snapshot and updated to the latest version of
filter-rspamd and everything is working again! Thank you for your
follow-up, time and attention!
Best,
Matt

**Comment by whataboutpereira** [comment]
Curious. I’ve been running all the filter releases (on CentOS 7) with Rspamd 1.9-2.2 without problems.

**Comment by whataboutpereira** [comment]
Ahh, nice timing. Good luck! ;)

**Comment by whataboutpereira** [comment]
Maybe Gilles can confirm if the current snapshot includes the filter API bump from 0.4 to 0.5, that needed a change in the filter.

**Comment by ghost** [comment]
Either way I am happy as a clam that it's working again. I was thinking
about trying to write a python script in the interim just so I can have
spam checking and, voila, Gilles et al worked their magic.
