### ISSUE TITLE
Greylist issue in combination with disabled greylisting in Rspamd.

### ISSUE THREAD

**Issue by whataboutpereira** [poolpOrg/filter-rspamd#31]
I'm finding that if you overwrite the greylist action in Rspamd local.d/actions.conf and then disable greylisting, Rspamd will blindly return 'greylist' action instead of the actual greylist module action which is 'soft reject'.

I'm wondering if the filter should respond to 'greylist' action at all, because it's not the action that Rspamd returns from its greylist module. 'soft reject' should probably be the only action the filter accepts for a temporary reject.

**Comment by poolpOrg** [comment]
I'm unsure I understand, care to elaborate ?

**Comment by whataboutpereira** [comment]
The action Rspamd returns for greylisted messages is "soft reject".

The filter however also soft rejects messages with "greylist" action.

There is a special case in Rspamd where it returns "greylist" action and that is pretty much when greylisting is actually disabled (and you've defined the "greylist" action threshold in local config).

https://github.com/rspamd/rspamd/issues/3295

**Comment by poolpOrg** [comment]
ok so 'greylist' should be considered as 'proceed' really ?

**Comment by whataboutpereira** [comment]
I think 'greylist' shouldn't be considered at all, because Rspamd greylisting doesn't use that word as an action name at all.

**Comment by whataboutpereira** [comment]
I see you're 3 minutes ahead of me there (https://github.com/poolpOrg/filter-rspamd/commit/d62fac3c94af26f7e60cff94800c5c0830321a3b). :)
