### ISSUE TITLE
filter-rspamd exits when tx-mail sends 4 params instead of 3

### ISSUE THREAD

**Issue by hblanks** [poolpOrg/filter-rspamd#32]
On a server running OpenSMTPD 6.6.4p1 with rspamd 2.2, I've had a couple smtpd shutdowns happen due to the filter-rspamd plugin reporting "invalid input, shouldn't happen."

After the second or third one, I swapped all `log.Fatal()` calls to `log.Fatalf()` with the params in the logging message, like so:

```
@@ -153,7 +153,7 @@ func txBegin(s *session, params []string) {
 
 func txMail(s *session, params []string) {
        if len(params) != 3 {
-               log.Fatal("invalid input, shouldn't happen")
+               log.Fatalf("invalid input, shouldn't happen: %v", params)
        }
 
        if params[2] != "ok" {
```

Which revealed that in some cases, at least, we're getting a `tx-mail` message with four params instead of three:

```
Mar 24 13:53:35 XXX smtpd[2268]: rspamd: 2020/03/24 13:53:35 txMail: invalid input, shouldn't happen: [0797092b CleaniX UVRaySanatizer@cleanixport.xyz ok]
```

Might you have any suggestions for why this would be the case, or how I could prepare a patch to handle this?

**Comment by hblanks** [comment]
FWIW, the patch I have just now is:

```go
diff --git a/filter-rspamd.go b/filter-rspamd.go
index 749d5ac..08c60a9 100644
--- a/filter-rspamd.go
+++ b/filter-rspamd.go
@@ -153,7 +153,16 @@ func txBegin(s *session, params []string) {
 
 func txMail(s *session, params []string) {
        if len(params) != 3 {
-               log.Fatal("invalid input, shouldn't happen")
+               // Handle email addresses with | in them, relying on
+               // the fact that first and last param can't contain |.
+               params = []string{
+                       params[0],
+                       strings.Join(params[1:len(params)-2], "|"),
+                       params[len(params)-1],
+               }
+       }
+       if len(params) != 3 {
+               log.Fatalf("invalid input, shouldn't happen: %v", params)
        }
 
        if params[2] != "ok" {
```

**Comment by lfos** [comment]
Maybe you can try to intercept the raw filter output for one of these lines and paste it here.

I am not very familiar with the filter code but it seems like OpenSMTPd should escape fields that contain `|`. If that's not the case, that is something that needs to be addressed in OpenSMTPd. In any case, we should improve the code to tokenize the messages and handle escaped characters properly.

**Comment by hblanks** [comment]
Thanks for the note! A few points.

> Maybe you can try to intercept the raw filter output for one of these lines and paste it here.

The `params` that I logged, using the patch in my first comment, is just the raw filter line split by `|` on [filter-rspamd.go:558](https://github.com/poolpOrg/filter-rspamd/blob/master/filter-rspamd.go#L558) so I think we can safely say that the filter input sent to us was:

```
0797092b|CleaniX|UVRaySanatizer@cleanixport.xyz|ok
```

I can go back and add more logging if you really need, but can also confirm that after applying the patch in my later comment, I have no longer had any exits of smtpd due to the filter dying.

> I am not very familiar with the filter code but it seems like OpenSMTPd should escape fields that contain |.

So, it turns out I did read through the code on this -- and best I can tell, it does not. I believe this is because the only input assumed to contain `|` was in the message body, which always goes at the end of a line. This reply by @poolpOrg suggests the same:

>> 8) What if the SMTP input/output or the filter input/output contains "|"
>> as a character - would the separator processing still work?
>>
>
> yes
>
> the protocol header fields have a fixed size and do not contain '|',
> only the last field may contain '|' so there's no ambiguity.

(https://www.mail-archive.com/misc@opensmtpd.org/msg04161.html)

Best I can guess, `tx-mail` was either not in place at the time of this reply, or @poolpOrg  had assumed that `|` was not allowed in email addresses when he picked `|` as the separator.

**Comment by lfos** [comment]
While your patch is a proper workaround, I think this should be addressed in the protocol to simplify parsing and avoid future breakage. Escaping the separator in the payload sounds like a reasonable solution. Maybe you could file a bug with OpenSMTPd?

**Comment by hblanks** [comment]
OK! Filed at https://github.com/OpenSMTPD/OpenSMTPD/issues/1041

I'm not sure if you want a PR that handles unescaped email addresses for the near term. (It seems like we'd need to handle not just `tx-mail`, but a few other report events as well.) If so, feel free to use what I have above as a starting point, or let me know and I may have time to prepare a patch for not just this case, but the remainder of ones, too.

**Comment by lfos** [comment]
It's up to @poolpOrg to decide but I personally think you should definitely submit a PR with your workaround because:

1. It's a reliability issue that we probably want to have fixed as soon as possible.
2. Having escape sequences added to the filter protocol likely requires a protocol version bump, so we still need to keep the workaround for backwards compatibility (at least for a while).

**Comment by lfos** [comment]
Before submitting the PR, please make sure the logic for testing the number or tokens is correct: if there are less than three parameters, we should display the previous error message, and if there are more than three parameters, any additional fields should be absorbed by the second one.

**Comment by poolpOrg** [comment]
mh, I need to dive back into this before I can comment, give me a couple days.

**Comment by poolpOrg** [comment]
Added a comment in:

https://github.com/OpenSMTPD/OpenSMTPD/issues/1041

The filter will be fixed accordingly after the fix is applied to OpenSMTPD.

**Comment by lfos** [comment]
We still need to add the workaround, too, if we want to retain backwards compatibility.

**Comment by poolpOrg** [comment]
Yes, this will be handled with backwards compat in mind

**Comment by poolpOrg** [comment]
can you test update your filter from branch master and confirm it works for you ?

**Comment by hblanks** [comment]
@poolpOrg - I have verified that a build from d62fac3c works, both for emails with typical "From:" header email addresses, and for emails where the From header's email contains `|`.

And, the 3 commits you pushed fixing this also read clean to me. Thank you for your work!
