### ISSUE TITLE
rspamd settings has wrong example

### ISSUE THREAD

**Issue by toxadx** [poolpOrg/filter-rspamd#38]
README contains wrong example of user settings.

```
outgoing {
    id = "outgoing";
    apply {
        enable_groups = ["dkim"];
        actions {
            reject = 100.0;
            greylist = 100.0;
            "add header" = 100.0;
        }
    }
}
```

enable_groups shall be written as groups_enabled. See documentation - https://rspamd.com/doc/configuration/settings.html

**Comment by poolpOrg** [comment]
sorry, missed this issue, example fixed thanks
