### ISSUE TITLE
rspamd: failed to decode JSON response (Rspamd v3.3)

### ISSUE THREAD

**Issue by whataboutpereira** [poolpOrg/filter-rspamd#41]
Just a heads up that I've encountered the following after updating Rspamd from v3.2 to v3.3 just now:

```
Oct  3 20:52:06 orc smtpd[212486]: info: OpenSMTPD 6.8.0p2 starting
Oct  3 20:52:15 orc smtpd[212491]: 03c6e38b6a06134d smtp connected address=10.0.8.2 host=<unknown>
Oct  3 20:52:15 orc smtpd[212491]: 03c6e38b6a06134d smtp tls ciphers=TLSv1.3:TLS_AES_256_GCM_SHA384:256
Oct  3 20:52:15 orc smtpd[212491]: 03c6e38b6a06134d smtp authentication user=test@host.name result=ok
Oct  3 20:52:15 orc smtpd[212490]: rspamd: failed to decode JSON response
Oct  3 20:52:15 orc smtpd[212491]: 03c6e38b6a06134d smtp failed-command command="DATA" result="421 server internal error"
```
Curiously incoming mails seem to work. Now how did this Go work... :)

**Comment by yeah-its-gloria** [comment]
The problem appears to be generally caused by an empty `add_headers` ([source](https://github.com/poolpOrg/filter-rspamd/blob/master/filter-rspamd.go#L73)) field.
The JSON unmarshaller doesn't want to turn this empty array into a `map[string]interface{}`, which is why the decoding fails.

**Comment by ziQ** [comment]
@whataboutpereira wrote:
> Curiously incoming mails seem to work. 

In my case, incoming mails don't come through with rspamd v3.3:
```
(...)
filter "rspamd"         proc-exec "filter-rspamd"
listen on enp4s0          port 25    hostname ...   tls-require   pki letsencrypt_certstuff   filter { check_dyndns, check_rdns, check_fcrdns, rspamd }
(...)
```

Logs look similar to yours, just that mine are without authentication (because they're inbound mails, not submissions)
```
Oct 08 17:35:26 vetinari smtpd[54111]: a4a1c4745f2d7646 smtp connected address=134.147.53.155 host=out3.mail.ruhr-uni-bochum.de
Oct 08 17:35:26 vetinari smtpd[54111]: a4a1c4745f2d7646 smtp tls ciphers=TLSv1.3:TLS_AES_256_GCM_SHA384:256
Oct 08 17:35:26 vetinari smtpd[54110]: rspamd: failed to decode JSON response
Oct 08 17:35:26 vetinari smtpd[54111]: a4a1c4745f2d7646 smtp failed-command command="DATA" result="421 server internal error"
Oct 08 17:35:26 vetinari smtpd[54111]: a4a1c4745f2d7646 smtp disconnected reason=quit
```

**Comment by ville-h** [comment]
I'm also hit by this issue. Recent upgrade to rspamd 3.3. Receiving and sending doesn't work. Any current work around to fix this?

**Comment by ziQ** [comment]
I temporarily disabled rspamd for inbound and outbound mails and switched my DKIM signing to `filter-dkimsign`.

**Comment by melua** [comment]
I have the same issue with rspamd-3.3 (Alpine package update), receiving and sending doesn't work.
Rspamd is critical for me (60% incoming spam) : had to downgrade to rspamd-3.2 to make it work again with this filter.

**Comment by ArchangeGabriel** [comment]
Same issue on sending on Arch after update, receiving works though.

EDIT: Actually receiving works partially only, as mails just don’t go through rspamd.

**Comment by vstakhov** [comment]
I think this change is caused by https://github.com/rspamd/rspamd/pull/4259. However, I don't understand why an empty array fails to unmarshal. As a workaround, it is probably possible to remove empty `add_headers` element.

**Comment by bitfehler** [comment]
May or may not be an option for others, but for me a viable workaround was to simply try to make sure that `add_headers` is never empty, using this `milter_headers.conf`:
```
# local.d/milter_headers.conf:

# Options

# Add "extended Rspamd headers" (default false) (enables x-spamd-result, x-rspamd-server & x-rspamd-queue-id routines)
extended_spam_headers = true;

# List of headers to be enabled for authenticated users (default empty)
authenticated_headers = ["authentication-results"];

# List of headers to be enabled for local IPs (default empty)
local_headers = ["x-spamd-bar"];

# Set false to always add headers for local IPs (default true)
skip_local = false;

# Set false to always add headers for authenticated users (default true)
skip_authenticated = false;

# Routines to use- this is the only required setting (may be omitted if using extended_spam_headers)
#use = ["x-spamd-bar", "authentication-results"];
```

**Comment by vstakhov** [comment]
Hum, does it work with this fix? TBH, Rspamd now returns a different thing: an array of headers to be added:

```json
 "add_headers": {
            "hoho": [
                {
                    "order": 1,
                    "value": "ohoho"
                },
                {
                    "order": 1,
                    "value": "ohohooo"
                }
            ],
            "hname": "X-SPAM-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "hash-2": [
                {
                    "order": -2,
                    "value": "string"
                }
            ],
```

It still looks quite inconsistent tbh, so I assume it must be fixed asap in Rspamd. The question is: what sort of fix would be enough...

**Comment by vstakhov** [comment]
From the code, this filter will not work with the format: https://github.com/poolpOrg/filter-rspamd/blob/master/filter-rspamd.go#L473 , so no headers will be added at all.

**Comment by vstakhov** [comment]
Ok, since this issue is clearly a breaking change from the Rspamd side that affects many users, I would suggest the following plan:

1. Restore back the compatible behaviour:
  * No arrays, when there is a single header, just an object like it is expected in this filter
  * No add_headers when there are no headers to add
2. Add an option to switch to the new behaviour (mostly about arrays all the time)
3. Release 3.4 with the proposed fix sooner, so Rspamd can be used properly

For now, the only way to fix this issue is to stay with 3.2 I'm afraid.

**Comment by whataboutpereira** [comment]
Thanks a lot for looking into it!

**Comment by zx2c4** [comment]
I guess Go expects a `{}` rather than a `[]`?

**Comment by vstakhov** [comment]
It should be fixed in the release 3.4, please update and confirm where possible.

**Comment by whataboutpereira** [comment]
Thanks! Works here!

**Comment by nomadlogic** [comment]
Works here as well - even managed to get PR for the FreeBSD ports tree accepted this morning.  Thanks again for getting this fixed!
