### ISSUE TITLE
No longer available as an OpenBSD package?

### ISSUE THREAD

**Issue by ghost** [poolpOrg/filter-rspamd#48]
Been using OpenSMTPD for a few years now and finally getting around to putting some proper spam filtering in place, however this filter is no longer available as a package on OpenBSD:

```
# pkg_info -Q opensmtpd
libopensmtpd-0.7
opensmtpd-extras-6.7.1v0
opensmtpd-extras-mysql-6.7.1p0v0
opensmtpd-extras-pgsql-6.7.1p0v0
opensmtpd-extras-python-6.7.1v0
opensmtpd-extras-redis-6.7.1v0
opensmtpd-filter-admdscrub-0.1
opensmtpd-filter-dkimsign-0.5p2
opensmtpd-filter-dnsbl-0.3
p5-OpenSMTPd-Filter-0.0.2
```

This is on `-current`: `OpenBSD 7.3-current (GENERIC) #1193: Sun Jun 18 09:32:39 MDT 2023`

**Comment by poolpOrg** [comment]
Whatever happened was fixed:

https://github.com/openbsd/ports/tree/master/mail/opensmtpd-filters/rspamd

I suspect this is because there was a golang regression back then with the syscall restrictions that prevented the filter from building, but it's no longer the case.
